name = "digital-twin-cmms"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "digital-twin-cmms-production"
database_id = "3d13f4ce-3a36-48b1-aab6-adf0717154e6"

[[r2_buckets]]
binding = "R2"
bucket_name = "digital-twin-cmms-models"
